Ignore unset local service key
gallery-so/go-gallery pull request #238
Opened 2022-01-25 04:17 UTC by Robinnnnn

2022-01-25 04:18 UTC, Robinnnnn commented on server/server.go
> -	if viper.GetString("ENV") != "production" || viper.GetString("ENV") != "development" {
main change 1 was getting rid of this line, since it always evaluates to true

2022-01-25 04:18 UTC, Robinnnnn commented on server/server.go
> +				logrus.Info("not using gcp storage client in local environment")
main change 2

2022-01-25 04:18 UTC, Robinnnnn commented on server/server.go
> +	client, err := storage.NewClient(ctx, option.WithCredentialsFile(appCredentials))
line 250 was just moved down here, git thinks it's an addition

2022-01-25 20:02 UTC, bennycio requested changes

2022-01-25 20:02 UTC, bennycio commented on server/server.go
> +	client, err := storage.NewClient(ctx, option.WithCredentialsFile(appCredentials))
I think maybe we could move some of the logic around to allow this to also continue working in the app engine environment. Right now if we always use the credentials file then this might not work in the app engine environment. Maybe we could do something like this:

```
 if env != local {
  client, err := storage.NewClient(ctx)
  ...
  return client
}
// now we can assume this is local env
appCredentials := viper.GetString("GOOGLE_APPLICATION_CREDENTIALS")
... // logic to check if credentials file exists somewhere
if credentialsFile != nil {
  client, err := storage.NewClient(ctx, option.WithCredentialsFile(appCredentials))
  ...
  return client
}
// no credentials file exists locally, lets just return nil instead of panicking
return nil

```

2022-01-28 22:15 UTC, jarrel-b commented on server/handler.go
> +	if storageClient != nil {
Just realized that this would prevent me from testing v2 routes. Would it make to have some sort of dummy client?

2022-01-28 22:45 UTC, merged